spring:
  data:
    mongodb:
      uri: mongodb+srv://pedrohcs1:vKQRgFHl4pVYjUqF@tennisshedule.my5rl.mongodb.net/
      database: tennis_scheduling
      authentication-database: admin
      auto-index-creation: true
  mvc:
    static-path-pattern: /static/**
